package org.tg.osgi.intelligence.plan;

import goalp.exputil.AbstractStudyCase;
import goalp.model.ArtifactBuilder;
import goalp.systems.RepositoryBuilder;

public class Planner extends AbstractStudyCase {

	@Override
	public void caseStudy() {
		// TODO Auto-generated method stub
		
	}

	@Override
	protected void setupEnvironment(RepositoryBuilder repositoryBuilder) {
		repositoryBuilder
		.add(
			ArtifactBuilder.create()
			.identification("unb.tg.osgi.g0")
			.provides("unb.tg.osgi.g0")
			.dependsOn("unb.tg.osgi.g1.api")
			.dependsOn("unb.tg.osgi.g2.api")
			.dependsOn("unb.tg.osgi.g3.api")
			.dependsOn("unb.tg.osgi.g4.api")
			.dependsOn("unb.tg.osgi.g5.api")
			.dependsOn("unb.tg.osgi.g1")
			.dependsOn("unb.tg.osgi.g2")
			.dependsOn("unb.tg.osgi.g3")
			.dependsOn("unb.tg.osgi.g4")
			.dependsOn("unb.tg.osgi.g5")
			.build())
		.add(
			ArtifactBuilder.create()
			.identification("unb.tg.osgi.g1.api")
			.provides("unb.tg.osgi.g1.api")
			.build())
		.add(
				ArtifactBuilder.create()
				.identification("unb.tg.osgi.g1.impl.p1")
				.provides("unb.tg.osgi.g1")
				.dependsOn("unb.tg.osgi.g1.api")
				.build())
		.add(
			ArtifactBuilder.create()
			.identification("unb.tg.osgi.g1.impl.p2")
			.provides("unb.tg.osgi.g1")
			.dependsOn("unb.tg.osgi.g1.api")
			.build())
		.add(
			ArtifactBuilder.create()
			.identification("unb.tg.osgi.g2.api")
			.provides("unb.tg.osgi.g2.api")
			.build())
		.add(
				ArtifactBuilder.create()
				.identification("unb.tg.osgi.g2.impl.p3")
				.provides("unb.tg.osgi.g2")
				.dependsOn("unb.tg.osgi.g2.api")
				.build())
		.add(
			ArtifactBuilder.create()
			.identification("unb.tg.osgi.g2.impl.p4")
			.provides("unb.tg.osgi.g2")
			.dependsOn("unb.tg.osgi.g2.impl.p4.p5.api")
			.dependsOn("unb.tg.osgi.g2.impl.p4.p6.api")
			.dependsOn("unb.tg.osgi.g2.impl.p4.p5")
			.dependsOn("unb.tg.osgi.g2.impl.p4.p6")
			.build())
		.add(
			ArtifactBuilder.create()
			.identification("unb.tg.osgi.g2.impl.p4.p5.api")
			.provides("unb.tg.osgi.g2.impl.p4.p5.api")
			.build())
		.add(
			ArtifactBuilder.create()
			.identification("unb.tg.osgi.g2.impl.p4.p5.impl")
			.provides("unb.tg.osgi.g2.impl.p4.p5")
			.dependsOn("unb.tg.osgi.g2.impl.p4.p5.api")
			.build())
		.add(
				ArtifactBuilder.create()
				.identification("unb.tg.osgi.g2.impl.p4.p6.api")
				.provides("unb.tg.osgi.g2.impl.p4.p6.api")
				.build())
		.add(
				ArtifactBuilder.create()
				.identification("unb.tg.osgi.g2.impl.p4.p6.impl")
				.provides("unb.tg.osgi.g2.impl.p4.p6")
				.dependsOn("unb.tg.osgi.g2.impl.p4.p6.api")
				.build())
		.add(
				ArtifactBuilder.create()
				.identification("unb.tg.osgi.g2.impl.p7")
				.provides("unb.tg.osgi.g2")
				.dependsOn("unb.tg.osgi.g1.api")
				.dependsOn("unb.tg.osgi.g2.api")
				.dependsOn("unb.tg.osgi.g2.impl.p7.p8.api")
				.dependsOn("unb.tg.osgi.g1")
				.dependsOn("unb.tg.osgi.g2.impl.p7.p8")
				.build())
		.add(
				ArtifactBuilder.create()
				.identification("unb.tg.osgi.g2.impl.p7.p8.api")
				.provides("unb.tg.osgi.g2.impl.p7.p8.api")
				.build())
		.add(
				ArtifactBuilder.create()
				.identification("unb.tg.osgi.g2.impl.p7.p8.impl")
				.provides("unb.tg.osgi.g2.impl.p7.p8")
				.dependsOn("unb.tg.osgi.g2.impl.p7.p8.api")
				.build())
		.add(
				ArtifactBuilder.create()
				.identification("unb.tg.osgi.g3.api")
				.provides("unb.tg.osgi.g3.api")
				.build())
		.add(
				ArtifactBuilder.create()
				.identification("unb.tg.osgi.g3.impl.p10")
				.provides("unb.tg.osgi.g3")
				.dependsOn("unb.tg.osgi.g3.api")
				.build())
		.add(
				ArtifactBuilder.create()
				.identification("unb.tg.osgi.g3.impl.p11")
				.provides("unb.tg.osgi.g3")
				.dependsOn("unb.tg.osgi.g3.api")
				.build())
		.add(
				ArtifactBuilder.create()
				.identification("unb.tg.osgi.g4.api")
				.provides("unb.tg.osgi.g4.api")
				.build())
		.add(
				ArtifactBuilder.create()
				.identification("unb.tg.osgi.g4.impl")
				.provides("unb.tg.osgi.g4")
				.dependsOn("unb.tg.osgi.g4.api")
				.dependsOn("unb.tg.osgi.g4.impl.p12.api")
				.dependsOn("unb.tg.osgi.g4.impl.p13.api")
				.dependsOn("unb.tg.osgi.g4.impl.p12")
				.dependsOn("unb.tg.osgi.g4.impl.p13")
				.build())
		.add(
				ArtifactBuilder.create()
				.identification("unb.tg.osgi.g4.impl.p12.api")
				.provides("unb.tg.osgi.g4.impl.p12.api")
				.build())
		.add(
				ArtifactBuilder.create()
				.identification("unb.tg.osgi.g4.impl.p12.impl")
				.provides("unb.tg.osgi.g4.impl.p12")
				.dependsOn("unb.tg.osgi.g4.impl.p12.api")
				.build())
		.add(
				ArtifactBuilder.create()
				.identification("unb.tg.osgi.g4.impl.p13.api")
				.provides("unb.tg.osgi.g4.impl.p13.api")
				.build())
		.add(
				ArtifactBuilder.create()
				.identification("unb.tg.osgi.g4.impl.p13.impl")
				.provides("unb.tg.osgi.g4.impl.p13")
				.dependsOn("unb.tg.osgi.g4.impl.p13.api")
				.build())
		.add(
				ArtifactBuilder.create()
				.identification("unb.tg.osgi.g5.api")
				.provides("unb.tg.osgi.g5.api")
				.build())
		.add(
				ArtifactBuilder.create()
				.identification("unb.tg.osgi.g5.impl.p14")
				.provides("unb.tg.osgi.g5")
				.dependsOn("unb.tg.osgi.g5.api")
				.build())
		.add(
				ArtifactBuilder.create()
				.identification("unb.tg.osgi.g5.impl.p15")
				.provides("unb.tg.osgi.g5")
				.dependsOn("unb.tg.osgi.g5.api")
				.dependsOn("unb.tg.osgi.g5.impl.p15.api")
				.dependsOn("unb.tg.osgi.g5.impl.p15")
				.build())
		.add(
				ArtifactBuilder.create()
				.identification("unb.tg.osgi.g5.impl.p15.api")
				.provides("unb.tg.osgi.g5.impl.p15.api")
				.build())
		.add(
				ArtifactBuilder.create()
				.identification("unb.tg.osgi.g5.impl.p15.impl.p16")
				.provides("unb.tg.osgi.g5.impl.p15")
				.dependsOn("unb.tg.osgi.g5.impl.p15.api")
				.build())
		.add(
				ArtifactBuilder.create()
				.identification("unb.tg.osgi.g5.impl.p15.impl.p17")
				.provides("unb.tg.osgi.g5.impl.p15")
				.dependsOn("unb.tg.osgi.g5.impl.p15.api")
				.build())
		.add(
				ArtifactBuilder.create()
				.identification("unb.tg.osgi.g5.impl.p18")
				.provides("unb.tg.osgi.g5")
				.dependsOn("unb.tg.osgi.g5.api")
				.build());
	}

}
